name: "Build and test project"

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up JDK 16"
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Build project with Gradle"
        run: ./gradlew build --stacktrace
