name: "Build project"

on:
  push:
  #    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os-name: ubuntu
            gradle-task: packageDeb
          - os: windows-latest
            os-name: windows
            gradle-task: package
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Package project with Gradle"
        run: ./gradlew ${{ matrix.gradle-task }} --stacktrace
      - name: "Upload build packages"
        uses: actions/upload-artifact@v3
        with:
          name: package-${{ matrix.os-name }}
          path: build/bin/**

#  build-fedora-latest:
#    runs-on: ubuntu-latest
#    container: fedora:latest
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v3
#      - name: "Set up JDK 17"
#        uses: actions/setup-java@v2
#        with:
#          java-version: "17"
#          distribution: "adopt"
#      - name: "Grant execute permission for gradlew"
#        run: chmod +x gradlew
#      - name: "Build project with Gradle"
#        run: ./gradlew packageRpm --stacktrace
#      - name: "Upload build packages"
#        uses: actions/upload-artifact@v3
#        with:
#          name: package-fedora
#          path: build/bin/**
