name: "Check project"

on:
  push:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Check project with Gradle"
        run: ./gradlew check --stacktrace

#  check-fedora-latest:
#    runs-on: ubuntu-latest
#    container: fedora:latest
#    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v3
#      - name: "Set up JDK 17"
#        uses: actions/setup-java@v2
#        with:
#          java-version: "17"
#          distribution: "adopt"
#      - name: "Grant execute permission for gradlew"
#        run: chmod +x gradlew
#      - name: "Check project with Gradle"
#        run: ./gradlew check --stacktrace
