name: "Release web application"

on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Test web app"
        run: ./gradlew :app-web:allTests --stacktrace
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up JDK 17"
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Generate release distribution files with Gradle"
        run: >
          ./gradlew
          :app-web:wasmJsBrowserDistribution
          -Dorg.gradle.jvmargs=-Xmx2048m
          -Ddebug=false
          --stacktrace
      - name: "Deploy web application"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: site
          destination_dir: editor
          publish_dir: app-web/build/dist/wasmJs/productionExecutable
