name: "Release project"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Generate release jars with Gradle"
        run: ./gradlew proguardReleaseJars --stacktrace
      - name: "Print conveyor config"
        run: ./gradlew printConveyorConfig --stacktrace
      - name: "Download Conveyor"
        run: |
          wget https://downloads.hydraulic.dev/conveyor/conveyor-9.1-linux-amd64.tar.gz
          mkdir -p conveyor/install
          tar xzvf conveyor-9.1-linux-amd64.tar.gz -C conveyor/install
      - name: "Package and publish release"
        run: conveyor/install/conveyor-9.1/bin/conveyor make copied-site
        env:
          CONVEYOR_AGREE_TO_LICENSE: 1
          GH_CONVEYOR: ${{ secrets.GH_CONVEYOR }}
