name: "Release project"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Generate release jars with Gradle"
        run: ./gradlew proguardReleaseJars -Ddeploy=true --stacktrace
      - name: "Render and print Conveyor config"
        uses: hydraulic-software/conveyor/actions/build@v11.1
        with:
          command: json
          extra_flags: --file=app-desktop/conveyor.conf
          agree_to_license: 1
          signing_key: ${{ secrets.CONVEYOR_SIGNING_KEY }}
        env:
          GH_CONVEYOR: ${{ secrets.GH_CONVEYOR }}
      - name: "Package and publish release"
        uses: hydraulic-software/conveyor/actions/build@v11.1
        with:
          command: make copied-site
          extra_flags: --file=app-desktop/conveyor.conf
          agree_to_license: 1
          signing_key: ${{ secrets.CONVEYOR_SIGNING_KEY }}
        env:
          GH_CONVEYOR: ${{ secrets.GH_CONVEYOR }}
